### ISSUE TITLE
ModuleNotFoundError (chromosomesearch_pb2) in search microservice

### ISSUE THREAD

**Issue by nathanweeks** [legumeinfo/lis_context_viewer#325]
Merged 967af39c0eaa09b5c3efb144830ddfaaf605ff95 into docker-redisearch, then:
```
$ docker-compose up -d --build search
...
$ docker-compose ps
                  Name                                Command                  State               Ports         
-----------------------------------------------------------------------------------------------------------------
lis_context_viewer_chado_to_redisearch_1   python3 chado_to_redisearc ...   Exit 0                               
lis_context_viewer_db_1                    docker-entrypoint.sh postgres    Up (healthy)   5432/tcp              
lis_context_viewer_gene_search_1           python3 microservice.py -- ...   Up             0.0.0.0:8080->8080/tcp
lis_context_viewer_redisearch_1            docker-entrypoint.sh redis ...   Up (healthy)   6379/tcp              
lis_context_viewer_search_1                python3 microservice.py -- ...   Exit 1                               
$ docker-compose logs search
Attaching to lis_context_viewer_search_1
search_1               | Traceback (most recent call last):
search_1               |   File "microservice.py", line 8, in <module>
search_1               |     from grpc_client import GENE_SEARCH_ADDR, CHROMOSOME_SEARCH_ADDR
search_1               |   File "/app/grpc_client.py", line 8, in <module>
search_1               |     import chromosomesearch_pb2
search_1               | ModuleNotFoundError: No module named 'chromosomesearch_pb2'
```
Indeed, no chromosomesearch_pb2.py in search/microservices/search

**Comment by alancleary** [comment]
Whoops. I forgot to add the new auto-generated gRPC files to the search service. Fixed in commit c06d69799f70bc2014f358fb8e110ad0ba2dcbcf.
